### ISSUE TITLE
Wrong uploadPath cause Nodebb crash

### ISSUE THREAD

**Issue by Genteure** [vishnu667/nodebb-plugin-local-image-upload#5]
```
Error: ENOENT: no such file or directory, mkdir '/opt/nodebb/opt/nodebb/public/uploads/files/1'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at /opt/nodebb/node_modules/nodebb-plugin-local-image-upload/index.js:29:24
    at fn (/opt/nodebb/node_modules/.1.5.2@async/lib/async.js:746:34)
    at /opt/nodebb/node_modules/.1.5.2@async/lib/async.js:1213:16
    at /opt/nodebb/node_modules/.1.5.2@async/lib/async.js:166:37
    at /opt/nodebb/node_modules/.1.5.2@async/lib/async.js:706:43
    at /opt/nodebb/node_modules/.1.5.2@async/lib/async.js:167:37
    at Object.async.waterfall (/opt/nodebb/node_modules/.1.5.2@async/lib/async.js:710:44)
    at Object.plugin.upload [as method] (/opt/nodebb/node_modules/nodebb-plugin-local-image-upload/index.js:23:15)
    at /opt/nodebb/src/plugins/hooks.js:120:12
    at /opt/nodebb/node_modules/.1.5.2@async/lib/async.js:375:13
    at iterate (/opt/nodebb/node_modules/.1.5.2@async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/opt/nodebb/node_modules/.1.5.2@async/lib/async.js:281:9)
    at Object.async.inject.async.foldl.async.reduce (/opt/nodebb/node_modules/.1.5.2@async/lib/async.js:374:15)
    at fireFilterHook (/opt/nodebb/src/plugins/hooks.js:112:9)
    at Object.Plugins.fireHook (/opt/nodebb/src/plugins/hooks.js:93:4)
    at /opt/nodebb/src/controllers/uploads.js:61:20
    at fn (/opt/nodebb/node_modules/.1.5.2@async/lib/async.js:746:34)
    at /opt/nodebb/node_modules/.1.5.2@async/lib/async.js:1213:16
    at /opt/nodebb/node_modules/.1.5.2@async/lib/async.js:166:37
    at /opt/nodebb/node_modules/.1.5.2@async/lib/async.js:706:43
```
You might want to change [index.js#27](https://github.com/vishnu667/nodebb-plugin-local-image-upload/blob/master/index.js#L27) from
```javascript
var uploadPath = path.join(nconf.get('base_dir'), nconf.get('upload_path'), folder, ''+uid);
```
to
```javascript
var uploadPath = path.join(nconf.get('upload_path'), folder, ''+uid);
```

**Comment by smartameer** [comment]
Fixed upload path #6
